version: "3.8"

services:
  app:
    container_name: app
    build: ./
    ports:
      - 3000:3000
    env_file:
      - secrets.env
    depends_on:
      - nats
      - db
    networks:
      - app_network

  db:
    image: postgres:15
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    ports:
      - 5432:5432
    container_name: postgres
    environment:
      - POSTGRES_USER=prr133f
      - POSTGRES_PASSWORD=123arra321
      - POSTGRES_DB=l0
    volumes:
      - database_postgres:/var/lib/postgresql/data
    networks:
      - app_network
    
  nats:
    image: nats
    expose:
      - 8222
    ports:
      - 4222:4222
      - 8222:8222
    command: ["-js", "--server_name", "test", "--http_port", "8222"]
    environment:
      - NATS_USER=local
      - NATS_PASSWORD=9t5lIAFKJXY2nr5C524HgGsQjNStoplG
    networks:
      - app_network

volumes:
  database_postgres:

networks:
  app_network:
    driver: bridge
